import {
  WidgetType,
  WidgetSize,
  Widget,
} from "@/app/[locale]/dashboard/types/dashboard";
import { DashboardLayoutWithWidgets } from "@/store/user-store";

export const defaultLayouts: DashboardLayoutWithWidgets = {
  id: "",
  userId: "",
  createdAt: new Date(),
  updatedAt: new Date(),
  desktop: [
    {
      i: "widget1751403095730",
      type: "calendarWidget",
      size: "large",
      x: 0,
      y: 17,
      w: 6,
      h: 8,
    },
    {
      i: "widget1751715494609",
      type: "tradeDistribution",
      size: "small",
      x: 0,
      y: 1,
      w: 3,
      h: 4,
    },
    {
      i: "widget1751741589330",
      type: "pnlChart",
      size: "medium",
      x: 6,
      y: 9,
      w: 6,
      h: 4,
    },
    {
      i: "widget1752135357688",
      type: "weekdayPnlChart",
      size: "small",
      x: 3,
      y: 5,
      w: 3,
      h: 4,
    },
    {
      i: "widget1752135359621",
      type: "timeOfDayChart",
      size: "small",
      x: 6,
      y: 13,
      w: 3,
      h: 4,
    },
    {
      i: "widget1752135361015",
      type: "timeInPositionChart",
      size: "small",
      x: 9,
      y: 13,
      w: 3,
      h: 4,
    },
    {
      i: "widget1752135363430",
      type: "equityChart",
      size: "large",
      x: 6,
      y: 1,
      w: 6,
      h: 8,
    },
    {
      i: "widget1752135365730",
      type: "pnlBySideChart",
      size: "small",
      x: 9,
      y: 17,
      w: 3,
      h: 4,
    },
    {
      i: "widget1752135368429",
      type: "tickDistribution",
      size: "medium",
      x: 6,
      y: 21,
      w: 6,
      h: 4,
    },
    {
      i: "widget1752135370579",
      type: "commissionsPnl",
      size: "small",
      x: 3,
      y: 1,
      w: 3,
      h: 4,
    },
    {
      i: "widget1752135378584",
      type: "timeRangePerformance",
      size: "small",
      x: 0,
      y: 5,
      w: 3,
      h: 4,
    },
    {
      i: "widget1752135395916",
      type: "riskRewardRatio",
      size: "tiny",
      x: 9,
      y: 0,
      w: 3,
      h: 1,
    },
    {
      i: "widget1752135396857",
      type: "statisticsWidget",
      size: "medium",
      x: 0,
      y: 13,
      w: 6,
      h: 4,
    },
    {
      i: "widget1752135397611",
      type: "profitFactor",
      size: "tiny",
      x: 6,
      y: 0,
      w: 3,
      h: 1,
    },
    {
      i: "widget1762369988555",
      type: "averagePositionTime",
      size: "tiny",
      x: 3,
      y: 0,
      w: 3,
      h: 1,
    },
    {
      i: "widget1762369989742",
      type: "cumulativePnl",
      size: "tiny",
      x: 0,
      y: 0,
      w: 3,
      h: 1,
    },
    {
      i: "widget1762520220168",
      type: "pnlPerContractChart",
      size: "small",
      x: 6,
      y: 17,
      w: 3,
      h: 4,
    },
    {
      i: "widget1762520253990",
      type: "pnlPerContractDailyChart",
      size: "medium",
      x: 0,
      y: 9,
      w: 6,
      h: 4,
    },
    // ── Advanced statistics row ─────────────────────────────────────────────
    {
      i: "widget1770000000001",
      type: "expectancyCard",
      size: "tiny",
      x: 0,
      y: 25,
      w: 4,
      h: 1,
    },
    {
      i: "widget1770000000002",
      type: "sharpeCard",
      size: "tiny",
      x: 4,
      y: 25,
      w: 4,
      h: 1,
    },
    {
      i: "widget1770000000003",
      type: "maxDrawdownCard",
      size: "tiny",
      x: 8,
      y: 25,
      w: 4,
      h: 1,
    },
    // ── MFE/MAE & Rolling chart row ─────────────────────────────────────────
    {
      i: "widget1770000000004",
      type: "mfeMaeScatter",
      size: "large",
      x: 0,
      y: 26,
      w: 6,
      h: 8,
    },
    {
      i: "widget1770000000005",
      type: "rollingStatisticsChart",
      size: "large",
      x: 6,
      y: 26,
      w: 6,
      h: 8,
    },
    // ── Setup breakdown full-width row ──────────────────────────────────────
    {
      i: "widget1770000000006",
      type: "setupBreakdownTable",
      size: "extra-large",
      x: 0,
      y: 34,
      w: 12,
      h: 8,
    },
    // ── Monte Carlo simulation ───────────────────────────────────────────
    {
      i: "widget1770000000007",
      type: "monteCarloWidget",
      size: "large",
      x: 0,
      y: 42,
      w: 12,
      h: 14,
    },
  ],
  mobile: [
    {
      i: "calendarWidget",
      type: "calendarWidget" as WidgetType,
      size: "large" as WidgetSize,
      x: 0,
      y: 2,
      w: 12,
      h: 6,
    },
    {
      i: "equityChart",
      type: "equityChart" as WidgetType,
      size: "medium" as WidgetSize,
      x: 0,
      y: 8,
      w: 12,
      h: 6,
    },
    {
      i: "cumulativePnl",
      type: "cumulativePnl" as WidgetType,
      size: "tiny" as WidgetSize,
      x: 0,
      y: 0,
      w: 12,
      h: 1,
    },
    {
      i: "tradePerformance",
      type: "tradePerformance" as WidgetType,
      size: "tiny" as WidgetSize,
      x: 0,
      y: 1,
      w: 12,
      h: 1,
    },
  ],
};